---
- name: Deluge requierement installed
  hosts: all

  tasks:
  - name: latest Python version installed
    dnf:
      name: python
      state: latest
      
  - name: latest Python-twisted version installed
    dnf:
      name: python-twisted
      state: latest

  - name: latest python-openssl version installed
    dnf:
      name: python-openssl
      state: latest
      
  - name: latest python-setuptools version installed
    dnf:
      name: python-setuptools
      state: latest

  - name: latest intltool version installed
    dnf:
      name: intltool
      state: latest

  - name: latest python-xdg version installed
    dnf:
      name: python-xdg
      state: latest

  - name: latest python-chardet version installed
    dnf:
      name: python-chardet
      state: latest

  - name: latest geoip-database version installed
    dnf:
      name: geoip-database
      state: latest

  - name: latest python-libtorrent version installed
    dnf:
      name: python-libtorrent
      state: latest

  - name: latest python-notify version installed
    dnf:
      name: python-notify
      state: latest

  - name: latest python-pygame version installed
    dnf:
      name: python-pygame
      state: latest

  - name: latest python-glade2 version installed
    dnf:
      name: python-glade2
      state: latest

  - name: latest librsvg2-common version installed
    dnf:
      name: librsvg2-common
      state: latest

  - name: latest xdg-utils version installed
    dnf:
      name: xdg-utils
      state: latest

  - name: latest python-mako version installed
    dnf:
      name: python-mako
      state: latest
    
